# Generated by Django 5.0 on 2023-12-14 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 9, 30, 5, 812686, tzinfo=datetime.timezone.utc)),
        ),
    ]
