# Generated by Django 5.0 on 2023-12-14 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_user_managers_alter_task_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 9, 35, 2, 38598, tzinfo=datetime.timezone.utc)),
        ),
    ]
