# Generated by Django 5.0 on 2023-12-17 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_task_task_due'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 17, 8, 25, 57, 428557, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
