# Generated by Django 5.0 on 2023-12-17 08:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_user_options_alter_task_task_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
