# Generated by Django 5.0 on 2023-12-19 07:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_task_task_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_due',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Task due time'),
        ),
    ]
