# Generated by Django 5.0 on 2023-12-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-task_due']},
        ),
    ]
