# Generated by Django 5.0 on 2023-12-31 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_due']},
        ),
    ]
